### PR TITLE
Update README.md

### LINKED ISSUE #2: Update README.md

### PR DESCRIPTION
**Pull request by ashiscs**
fixes #2

### CODE REVIEW

**Comment by ashiscs** [comment]
@SMD-7 sir can you review

**Review by SMD-7 — APPROVED** [review]
Looks fine for now, will have to update with new details as early as possible.

**Comment by SMD-7** [comment]
@ashiscs very fast 👍

**Comment by ashiscs** [comment]
> @ashiscs very fast 👍

Thank you, sir!

**Pull request merged**
